### ISSUE TITLE
An error occurred  medflix 

### ISSUE THREAD

**Issue by Doctor2023** [mohdje/medflix#3] opened 2023-06-26 17:22 UTC
![IMG_0668](https://github.com/mohdje/medflix/assets/129991276/ef8b8039-6ec0-4aa0-845a-572fa2a824f6)

I can't play the movies and series, I can't play with vlc either, the error appears

An error occurred torrents

Please you can implement airplay on MEDFLIX

in version mac

**Comment by mohdje** [comment] 2023-06-30 13:52
In the app folder, go to Contents/MacOS, you should be able to see a "error.txt" file. Just paste here the traces so I can see what is the issue.
Also did you try with several movies and series ? Because sometimes the torrent magnet or torrent file link is dead and causes this error message to be displayed.

**Comment by Doctor2023** [comment] 2023-06-30 17:53
![20230630_194937](https://github.com/mohdje/medflix/assets/129991276/eb0c3a3f-69ac-414c-9be2-75cfb1511172)

now I get this message it does not open it does not let me enter my mac computer

**Comment by Doctor2023** [comment] 2023-06-30 17:56
> 
I can't see the movies and series I know that loading download and the video doesn't come out and I change the quality of the videos the videos of the movies and torrent series don't come out and airplay is not available to process with apple tv

**Comment by Doctor2023** [comment] 2023-06-30 17:57
> In the app folder, go to Contents/MacOS, you should be able to see a "error.txt" file. Just paste here the traces so I can see what is the issue. Also did you try with several movies and series ? Because sometimes the torrent magnet or torrent file link is dead and causes this error message to be displayed.

I can't see the movies and series I know that loading download and the video doesn't come out and I change the quality of the videos the videos of the movies and torrent series don't come out and airplay is not available to process with apple tv

**Comment by mohdje** [comment] 2023-07-04 08:23
Please send me the traces that are in error.txt. Without those logs there is nothing I can do.

**Comment by Doctor2023** [comment] 2023-07-05 14:35
> Please send me the traces that are in error.txt. Without those logs there is nothing I can do.

please  airplay medflix apple tv  implement

**Comment by mohdje** [comment] 2023-07-08 10:43
Without traces there is no fix possible because the issue is unknown. I close the issue.

**Closed as completed by mohdje** 2023-07-08 10:43 UTC
